Repository CSIEHaTerX/Dr.UML, pull requests merged in 2025-04, with the labels that each got.

#47 Stuff shared by both Gadget and Association
  app/backend/component/attribute/attribute.go
  app/backend/component/attribute/attribute_test.go
  app/backend/component/attribute/textstyle.go
  app/backend/component/component.go
  app/backend/component/propertyTree.go
Labels: enhancement

#56 fix(typo): add . bcz it works
  .github/workflows/go-test.yml
Labels: sussy baka

#64 unfuck-GH-Action
  .github/workflows/go-test.yml
  app/backend/component/attribute/attribute_test.go
  app/backend/utils/textlength.go
  app/backend/utils/textlength_test.go
Labels: bug, sussy baka
